services:
    kuntu-docs:
        container_name: kuntu-docs
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.kuntu-docs.rule=Host(`docs.kuntu.shop`)"
        depends_on:
          - traefik
        networks:
          - traefik
        restart: unless-stopped

networks:
  traefik:
    external: true